[package]
name = "dev_caloptreyx_versionchanger"
description = "Switch a Minecraft server to any server type, version and build listed on mcjars."
authors = ["Caloptreyx"]
version = "0.1.0"
edition = { workspace = true }

[dependencies]
shared = { workspace = true }
wings-api = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
axum = { workspace = true }
garde = { workspace = true }
compact_str = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
indexmap = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
url = { workspace = true }

[dev-dependencies]
rmp-serde = { workspace = true }
